kind: ConfigMap
apiVersion: v1
metadata: # kpt-merge: local-path-storage/local-path-config
  name: local-path-config
  namespace: local-path-storage
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|local-path-storage|local-path-config'
    nephio.org/cluster-name: nephio-workload-cluster
data:
  config.json: |-
    {
            "nodePathMap":[
            {
                    "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                    "paths":["/opt/local-path-provisioner"]
            }
            ]
    }
  setup: |-
    #!/bin/sh
    set -eu
    mkdir -m 0777 -p "$VOL_DIR"
  teardown: |-
    #!/bin/sh
    set -eu
    rm -rf "$VOL_DIR"
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      containers:
      - name: helper-pod
        image: busybox
        imagePullPolicy: IfNotPresent
