apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: # kpt-merge: /local-path
  name: local-path
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    internal.kpt.dev/upstream-identifier: 'storage.k8s.io|StorageClass|default|local-path'
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
