kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata: # kpt-merge: /kindnet
  name: kindnet
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|ClusterRole|default|kindnet'
    nephio.org/cluster-name: nephio-workload-cluster
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
